#!/usr/bin/env bash

DEFAULT_NAME="projet"
G=false
S=false
B=false
A=false
T=false
SC=false

help () {
   echo "usage: code-html [--help] [-g | --git] [-s | --sass] [--scss] [-b | --bootstrap] [-a | --awesome] <folder>"
   echo "Create a project with an html structure and open it with Visual Studio Code."
}

check_folder () {
    if [ -z "$1" ] || [[ "${@: -1}" == -* ]] ; then
        FOLDER=$DEFAULT_NAME
    else
        FOLDER="${@: -1}"
    fi
}

opts_flag () {
    while getopts "gsba-:" opt; do
        case "$opt" in
            -)
                case ${OPTARG} in
                    help)       help
                                exit ;;
                    git)        G=true ;;
                    sass)       S=true ;;
                    bootstrap)  B=true ;;
                    awesome)    A=true ;;
                    typescript) T=true ;;
                    scss)       SC=true ;;
                esac ;;
            g) G=true ;;
            s) S=true ;;
            b) B=true ;;
            a) A=true ;;
            *) : ;;
        esac
    done
}

html_project () {
    mkdir "$FOLDER"
    cd "$FOLDER"
    mkdir -p assets/{css,img,js}
    touch index.html assets/css/style.css
}

add_git () {
    git init ./
    [[ "$OSTYPE" == "darwin"* ]] && echo ".DS_Store" >> .gitignore
    if [ "$A" = true ] || [ "$B" = true ] ; then
        echo "node_modules" >> .gitignore
        mkdir docs
        # echo "#"$FOLDER >> docs/README.md
    fi
}

add_sass () {
    type="sass"
    if [ "$SC" = true ] ; then
        type="scss"

    fi
    mkdir -p src/$type
    touch src/$type/style.$type
    # sass --watch src/sass/style.sass public/css/style.css
    [ "$G" = true ] && echo "style.css.map" >> .gitignore
    if [ "$B" = true ] ; then
        touch src/$type/bootstrap.$type
        touch src/$type/_variables.$type
        [ "$G" = true ] && echo "bootstrap.css.map" >> .gitignore
    fi
}

add_scss () {
    mkdir -p src/scss
    touch src/scss/style.scss
    # sass --watch src/scss/style.sass assets/scss/style.css
    [ "$G" = true ] && echo "style.css.map" >> .gitignore
    if [ "$B" = true ] ; then
        touch src/scss/bootstrap.sass
        touch src/scss/_variables.sass
        [ "$G" = true ] && echo "bootstrap.css.map" >> .gitignore
    fi
}

add_awesome () {
    npm install @fortawesome/fontawesome-free
}

add_bootstrap () {
    npm install @popperjs/core@^2.5.4
    npm install bootstrap@next
}

add_typescript () {
    touch tsconfig.json
    mkdir -p src/ts
    touch src/ts/main.ts
    # tsc -w
}

opts_flag "$@"
check_folder "$@"
html_project

[ "$B" = true ] || [ "$A" = true ] && npm init -y
[ "$B" = true ] && add_bootstrap
[ "$A" = true ] && add_awesome
[ "$G" = true ] && add_git
[ "$S" = true ] || [ "$SC" = true ] && add_sass
[ "$T" = true ] && add_typescript

code ./
