#!/usr/bin/env bash

DEFAULT_NAME="projet"
G=false
S=false
B=false
A=false

help () {
   echo "usage: code-html [--help] [-g | --git] [-s | --scss] [-b | --bootstrap] [-a | --awesome] [-r | --react] <folder>"
   echo "Create a project with an react and open it with Visual Studio Code."
}

opts_flag () {
    while getopts "sba-:" opt; do
        case "$opt" in
            -)
                case ${OPTARG} in
                    help)       help
                                exit ;;
                    git)        G=true ;;
                    bootstrap)  B=true ;;
                    awesome)    A=true ;;
                    scss)       S=true ;;
                esac ;;
            s) S=true ;;
            b) B=true ;;
            a) A=true ;;
            *) : ;;
        esac
    done
}

check_folder () {
    if [ -z "$1" ] || [[ "${@: -1}" == -* ]] ; then
        FOLDER=$DEFAULT_NAME
    else
        FOLDER="${@: -1}"
    fi
}

create_react () {
    npx create-react-app "$FOLDER"
    cd "$FOLDER"
    rm -rf ./public/{logo192.png,logo512.png,manifest.json,robots.txt}
    rm -rf ./src/{App.test.js,index.css,logo.svg,reportWebVitals.js,setupTests.js}
    mkdir ./src/components
}

add_awesome () {
    npm install @fortawesome/fontawesome-free
}

add_bootstrap () {
    npm install bootstrap@next
}

opts_flag "$@"
check_folder "$@"
create_react

[ "$B" = true ] && add_bootstrap
[ "$A" = true ] && add_awesome

code ./
