#!/usr/bin/env bash

DEFAULT_NAME="projet"
G=false
S=false
B=false
A=false
T=false

help () {
   echo "usage: code-laravel [--help] [-g | --git] [-s | --scss] [-b | --bootstrap] [-a | --awesome] <folder>"
   echo "Create a laravel project and open it with Visual Studio Code."
}

check_folder () {
    if [ -z "$1" ] || [[ "${@: -1}" == -* ]] ; then
        FOLDER=$DEFAULT_NAME
    else
        FOLDER="${@: -1}"
    fi
}

opts_flag () {
    while getopts "gsba-:" opt; do
        case "$opt" in
            -)
                case ${OPTARG} in
                    help)       help
                                exit ;;
                    git)        G=true ;;
                    bootstrap)  B=true ;;
                    awesome)    A=true ;;
                    scss)       S=true ;;
                    react)      R=true ;;
                esac ;;
            g) G=true ;;
            s) S=true ;;
            b) B=true ;;
            a) A=true ;;
            r) R=true ;;
            *) : ;;
        esac
    done
}

add_git () {
    git init ./
    [[ "$OSTYPE" == "darwin"* ]] && echo ".DS_Store" >> .gitignore
    if [ "$A" = true ] || [ "$B" = true ] ; then
        echo "node_modules" >> .gitignore
        mkdir docs
        # echo "#"$FOLDER >> docs/README.md
    fi
}

add_scss () {
    type="scss"
    mkdir -p src/$type
    touch src/$type/style.$type
    # sass --watch src/sass/style.sass public/css/style.css
    [ "$G" = true ] && echo "style.css.map" >> .gitignore
    if [ "$B" = true ] ; then
        touch src/$type/bootstrap.$type
        touch src/$type/_variables.$type
        [ "$G" = true ] && echo "bootstrap.css.map" >> .gitignore
    fi
}

add_awesome () {
    npm install @fortawesome/fontawesome-free
}

add_bootstrap () {
    composer require laravel/ui
    php artisan ui bootstrap
    # modifier bootstrap to 5.0! to do
    npm install @popperjs/core
    npm install && npm run dev
    npm run dev
}

create_laravel () {
    laravel new "$FOLDER"
}

opts_flag "$@"
check_folder "$@"
create_laravel

# [ "$B" = true ] || [ "$A" = true ] && npm init -y
# [ "$B" = true ] && add_bootstrap
# [ "$A" = true ] && add_awesome
# [ "$G" = true ] && add_git
# [ "$S" = true ] && add_scss

code ./
