#!/usr/bin/env bash

DEFAULT_NAME="projet"
B=false
A=false
bootstrap_version="^5.0.0-beta3" 


help () {
   echo "usage: code-laravel [--help] [-b version] [-auth] <folder>"
   echo "Create a laravel project and open it with Visual Studio Code."
}

check_folder () {
    if [ -z "$1" ] || [[ "${@: -1}" == -* ]] ; then
        FOLDER=$DEFAULT_NAME
    else
        FOLDER="${@: -1}"
    fi
}

opts_flag () {
    while getopts "b:-:" opt; do
        case "$opt" in
            -)
                case ${OPTARG} in
                    help)   help
                            exit ;;
                    auth)   A=true  ;;
                esac ;;
            b)  B=true
                if [[ ${OPTARG} != $FOLDER ]] ; then
                    bootstrap_version=${OPTARG}
                fi 
                ;;
            a)  A=true ;;
            *) : ;;
        esac
    done
}

add_bootstrap () {
    composer require laravel/ui
    php artisan ui bootstrap
    search="\"bootstrap\": \"^4.0.0\""
    replace="\"bootstrap\": \"$bootstrap_version\""
    sed -i "" "s/$search/$replace/" "package.json"
    npm install @popperjs/core
    npm install && npm run dev
    npm run dev
}

add_authentication () {
    composer require laravel/breeze
    php artisan breeze:install

    npm install
    npm run dev
    php artisan migrate
}

create_laravel () {
    # cd /Applications/MAMP/htdocs/
    laravel new "$FOLDER"
    cd "$FOLDER"
    database=$(echo "$FOLDER" | tr '-' '_')
    /Applications/MAMP/Library/bin/mysql -u root -p"root" -Bse "CREATE DATABASE $database; exit;"
}

check_folder "$@"
opts_flag "$@"


create_laravel
[ "$B" = true ] && add_bootstrap
[ "$A" = true ] && add_authentication


code ./
# php artisan serve
